### ISSUE TITLE
iOS 7.1 support ?

### ISSUE THREAD

**Issue by nicolasgoutaland** [zoonooz/ZFTokenField#10]
Hi there,

just a small question, why are you only supporting iOS 7.1, and not 7.0 ?

Regards,

**Comment by zoonooz** [comment]
@nicolasgoutaland I think I did not check it properly and it supposed to support 7.0 too. Anyway no one will use those versions right now. Sorry for laaaaaaaaate reply lol

**Comment by nicolasgoutaland** [comment]
\o/
