### ISSUE TITLE
If reduce height than 40 then its corner radius is effected.

### ISSUE THREAD

**Issue by qasimsqm** [zoonooz/ZFTokenField#11]
If TokenView height is 40 then it works fine but if i change it to 30 then it becomes edgy. I am unable to find it corner radius code. Can you please guide me what should i do?

**Comment by notDanish** [comment]
^same issue.

**Comment by qasimsqm** [comment]
@notDanish go to TokenView.xib, select view and click on 3rd tab on your right hand Identity inspector and see there will be an attribute of layer layer.cornerRadius, set this attribute value to the half size of your view and it will work :) happy coding

**Comment by notDanish** [comment]
@qasimsqm Thanks a lot brother! That solved it.
