### ISSUE TITLE
About the keyboard

### ISSUE THREAD

**Issue by leleron** [zoonooz/ZFTokenField#16]
when I push in the viewController secondly which contains the ZFTokenField, the keyboard will not show again. How to solve the problem?

**Comment by Pratik948** [comment]
Same issue!! Any workaround?

**Comment by zoonooz** [comment]
I could not reproduce this. Have you tried solutions from this http://stackoverflow.com/questions/8476021/trouble-shooting-becomefirstresponder-not-showing-keyboard-for-some-users
