### ISSUE TITLE
tokenField always has keyboard focus

### ISSUE THREAD

**Issue by dsngeu** [zoonooz/ZFTokenField#20]
in my project I have ZFTokenField and UITextView.
 when I tap on ZFTokenField and after that when I tap on UITextView then focus could not be get into UITextView, its always focus on  ZFTokenField

**Comment by ChiragKothiya1996** [comment]
hay @dsngeu how to resolve this issue

**Comment by dsngeu** [comment]
I have not find any solution so that I decided to change library, now I am using VENTokenField
