### ISSUE TITLE
the tokenfield doesn't increase size when full

### ISSUE THREAD

**Issue by bb-git** [zoonooz/ZFTokenField#4]
I am creating ZFTokenField programmatically, but the field doesn't increase size, when it's filled up with tokens. 
There is also a strange issue with the placeholder, it is only displaying the first 3 character of "Enter here".

**Comment by zeeshanbiit** [comment]
Its simple open your ZFTokenfield.m file and search for,
-(void)reloadData{}
In this function body you see this line,
self.textField.frame = (CGRect) {0,0,350,[self.dataSource lineHeightForTokenInField:self]};
In this line 350 is the writing text size you can set it with your desired size.
i think this will help you.
