### ISSUE TITLE
Token textfield frame is shifted inward with empty placeholder

### ISSUE THREAD

**Issue by nassifbasheer** [zoonooz/ZFTokenField#5]
Hi,

Thanks for the wonderful work you have done. 

If the token's textfield placeholder text is empty , the textfiled x origin is shifted inwards. ie if i set the placeholder text empty , and i start editing the text field, the initial text are not visible not . But however if i set 11 spaces or any anything in the range of 11 as the placeholder , the initial text is visible (frame is not shifted) .

**Comment by AlexNsbmr** [comment]
@nassifbasheer Did you found any workaround to use an empty placeholder?

**Comment by nassifbasheer** [comment]
@AlexNsbmr No , all i did was making a string of 11 spaces as placeholder    tokenField.textField.placeholder = @"           ";

**Comment by AlexNsbmr** [comment]
@nassifbasheer Ok, thanks for your answer.
